services:
  caddy:
    image: caddy:2.11.2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    network_mode: host
  ip-gate:
    build: ../
    image: polypode/ip-gate:latest
    network_mode: host
    env_file: ./.env
